version: "3"

services:

    # React
    app:
      image:  "${REGISTRY_HOST}/tms-portal"
      container_name: tms-portal
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        - './:/app'
        - '/app/node_modules'
      stdin_open: true
      ports:
        - 3000:3000
      env_file:
        - .env
              