name: CI - CD
on:
  push:
    branches: [ "main" ]

jobs:
  run-composer-and-docker:
    name: Continuous integration & Continuous Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
            path: '**/node_modules'
            key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
            
      - name: Install Dependencies
        run: yarn install
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: deploy
          file: "Dockerfile.prod"
          push: true
          tags: dziljalal/tms-portal:latest
          cache-from: type=registry,ref=dziljalal/tms-portal:latest
          cache-to: type=inline

