name: CI - CD
on:
  push:
    branches: [ "main" ]

jobs:
  run-composer-and-docker:
    name: Continuous integration & Continuous Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "Dockerfile.prod"
          push: true
          tags: dziljalal/tms-portal:latest
          cache-from: type=registry,ref=dziljalal/tms-portal:latest
          cache-to: type=inline

      - name: Remote SSH DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd portal
            docker-compose pull && docker-compose down && docker-compose up -d

